// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i24;
import 'dart:ui' as _i27;

import 'package:dio/dio.dart' as _i12;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i13;
import 'package:frontend/models/chat.dart' as _i17;
import 'package:frontend/models/comment.dart' as _i25;
import 'package:frontend/models/group_chat.dart' as _i21;
import 'package:frontend/models/map_pin.dart' as _i18;
import 'package:frontend/models/message.dart' as _i16;
import 'package:frontend/models/post.dart' as _i15;
import 'package:frontend/models/route.dart' as _i20;
import 'package:frontend/models/story.dart' as _i19;
import 'package:frontend/models/user.dart' as _i14;
import 'package:frontend/providers/auth_provider.dart' as _i26;
import 'package:frontend/providers/map_pin_provider.dart' as _i32;
import 'package:frontend/services/api_service.dart' as _i22;
import 'package:frontend/services/auth_api_service.dart' as _i2;
import 'package:frontend/services/chat_api_service.dart' as _i5;
import 'package:frontend/services/group_chat_api_service.dart' as _i11;
import 'package:frontend/services/location_api_service.dart' as _i7;
import 'package:frontend/services/location_service.dart' as _i29;
import 'package:frontend/services/map_pin_api_service.dart' as _i6;
import 'package:frontend/services/notification_api_service.dart' as _i8;
import 'package:frontend/services/post_api_service.dart' as _i4;
import 'package:frontend/services/route_api_service.dart' as _i10;
import 'package:frontend/services/socket_service.dart' as _i28;
import 'package:frontend/services/story_api_service.dart' as _i9;
import 'package:frontend/services/user_api_service.dart' as _i3;
import 'package:frontend/services/webrtc_service.dart' as _i31;
import 'package:geolocator/geolocator.dart' as _i30;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthApiService_0 extends _i1.SmartFake
    implements _i2.AuthApiService {
  _FakeAuthApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserApiService_1 extends _i1.SmartFake
    implements _i3.UserApiService {
  _FakeUserApiService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePostApiService_2 extends _i1.SmartFake
    implements _i4.PostApiService {
  _FakePostApiService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChatApiService_3 extends _i1.SmartFake
    implements _i5.ChatApiService {
  _FakeChatApiService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMapPinApiService_4 extends _i1.SmartFake
    implements _i6.MapPinApiService {
  _FakeMapPinApiService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocationApiService_5 extends _i1.SmartFake
    implements _i7.LocationApiService {
  _FakeLocationApiService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationApiService_6 extends _i1.SmartFake
    implements _i8.NotificationApiService {
  _FakeNotificationApiService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStoryApiService_7 extends _i1.SmartFake
    implements _i9.StoryApiService {
  _FakeStoryApiService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRouteApiService_8 extends _i1.SmartFake
    implements _i10.RouteApiService {
  _FakeRouteApiService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupChatApiService_9 extends _i1.SmartFake
    implements _i11.GroupChatApiService {
  _FakeGroupChatApiService_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_10 extends _i1.SmartFake implements _i12.Dio {
  _FakeDio_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFlutterSecureStorage_11 extends _i1.SmartFake
    implements _i13.FlutterSecureStorage {
  _FakeFlutterSecureStorage_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_12 extends _i1.SmartFake implements _i14.User {
  _FakeUser_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePost_13 extends _i1.SmartFake implements _i15.Post {
  _FakePost_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMessage_14 extends _i1.SmartFake implements _i16.Message {
  _FakeMessage_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChat_15 extends _i1.SmartFake implements _i17.Chat {
  _FakeChat_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMapPin_16 extends _i1.SmartFake implements _i18.MapPin {
  _FakeMapPin_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStory_17 extends _i1.SmartFake implements _i19.Story {
  _FakeStory_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRidersRoute_18 extends _i1.SmartFake implements _i20.RidersRoute {
  _FakeRidersRoute_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGroupChat_19 extends _i1.SmartFake implements _i21.GroupChat {
  _FakeGroupChat_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i22.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthApiService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAuthApiService_0(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i2.AuthApiService);

  @override
  _i3.UserApiService get users => (super.noSuchMethod(
        Invocation.getter(#users),
        returnValue: _FakeUserApiService_1(
          this,
          Invocation.getter(#users),
        ),
      ) as _i3.UserApiService);

  @override
  _i4.PostApiService get posts => (super.noSuchMethod(
        Invocation.getter(#posts),
        returnValue: _FakePostApiService_2(
          this,
          Invocation.getter(#posts),
        ),
      ) as _i4.PostApiService);

  @override
  _i5.ChatApiService get chats => (super.noSuchMethod(
        Invocation.getter(#chats),
        returnValue: _FakeChatApiService_3(
          this,
          Invocation.getter(#chats),
        ),
      ) as _i5.ChatApiService);

  @override
  _i6.MapPinApiService get mapPins => (super.noSuchMethod(
        Invocation.getter(#mapPins),
        returnValue: _FakeMapPinApiService_4(
          this,
          Invocation.getter(#mapPins),
        ),
      ) as _i6.MapPinApiService);

  @override
  _i7.LocationApiService get locations => (super.noSuchMethod(
        Invocation.getter(#locations),
        returnValue: _FakeLocationApiService_5(
          this,
          Invocation.getter(#locations),
        ),
      ) as _i7.LocationApiService);

  @override
  _i8.NotificationApiService get notifications => (super.noSuchMethod(
        Invocation.getter(#notifications),
        returnValue: _FakeNotificationApiService_6(
          this,
          Invocation.getter(#notifications),
        ),
      ) as _i8.NotificationApiService);

  @override
  _i9.StoryApiService get stories => (super.noSuchMethod(
        Invocation.getter(#stories),
        returnValue: _FakeStoryApiService_7(
          this,
          Invocation.getter(#stories),
        ),
      ) as _i9.StoryApiService);

  @override
  _i10.RouteApiService get routes => (super.noSuchMethod(
        Invocation.getter(#routes),
        returnValue: _FakeRouteApiService_8(
          this,
          Invocation.getter(#routes),
        ),
      ) as _i10.RouteApiService);

  @override
  _i11.GroupChatApiService get groupChats => (super.noSuchMethod(
        Invocation.getter(#groupChats),
        returnValue: _FakeGroupChatApiService_9(
          this,
          Invocation.getter(#groupChats),
        ),
      ) as _i11.GroupChatApiService);

  @override
  set auth(_i2.AuthApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #auth,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set users(_i3.UserApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #users,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set posts(_i4.PostApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #posts,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set chats(_i5.ChatApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #chats,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mapPins(_i6.MapPinApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #mapPins,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set locations(_i7.LocationApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #locations,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set notifications(_i8.NotificationApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #notifications,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set stories(_i9.StoryApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #stories,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set routes(_i10.RouteApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #routes,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set groupChats(_i11.GroupChatApiService? value) => super.noSuchMethod(
        Invocation.setter(
          #groupChats,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_10(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i12.Dio);

  @override
  _i13.FlutterSecureStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFlutterSecureStorage_11(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i13.FlutterSecureStorage);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  set dio(_i12.Dio? value) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<Map<String, dynamic>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i24.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i24.Future<Map<String, dynamic>>);

  @override
  _i24.Future<Map<String, dynamic>> register(
    String? username,
    String? email,
    String? password,
    String? fullName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            email,
            password,
            fullName,
          ],
        ),
        returnValue:
            _i24.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i24.Future<Map<String, dynamic>>);

  @override
  _i24.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i14.User> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i24.Future<_i14.User>.value(_FakeUser_12(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i24.Future<_i14.User>);

  @override
  _i24.Future<_i14.User> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i24.Future<_i14.User>.value(_FakeUser_12(
          this,
          Invocation.method(
            #getUser,
            [userId],
          ),
        )),
      ) as _i24.Future<_i14.User>);

  @override
  _i24.Future<_i14.User> updateProfile(
    String? fullName,
    String? bio, [
    Map<String, dynamic>? motorcycleInfo,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [
            fullName,
            bio,
            motorcycleInfo,
          ],
        ),
        returnValue: _i24.Future<_i14.User>.value(_FakeUser_12(
          this,
          Invocation.method(
            #updateProfile,
            [
              fullName,
              bio,
              motorcycleInfo,
            ],
          ),
        )),
      ) as _i24.Future<_i14.User>);

  @override
  _i24.Future<_i14.User> updateProfilePicture(String? imagePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfilePicture,
          [imagePath],
        ),
        returnValue: _i24.Future<_i14.User>.value(_FakeUser_12(
          this,
          Invocation.method(
            #updateProfilePicture,
            [imagePath],
          ),
        )),
      ) as _i24.Future<_i14.User>);

  @override
  _i24.Future<void> followUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [userId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> unfollowUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [userId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i14.User>> searchUsers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i24.Future<List<_i14.User>>.value(<_i14.User>[]),
      ) as _i24.Future<List<_i14.User>>);

  @override
  _i24.Future<_i14.User> updateUserStatus({
    required String? message,
    String? customText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserStatus,
          [],
          {
            #message: message,
            #customText: customText,
          },
        ),
        returnValue: _i24.Future<_i14.User>.value(_FakeUser_12(
          this,
          Invocation.method(
            #updateUserStatus,
            [],
            {
              #message: message,
              #customText: customText,
            },
          ),
        )),
      ) as _i24.Future<_i14.User>);

  @override
  _i24.Future<List<_i15.Post>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i24.Future<List<_i15.Post>>.value(<_i15.Post>[]),
      ) as _i24.Future<List<_i15.Post>>);

  @override
  _i24.Future<List<_i15.Post>> getExplorePosts({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExplorePosts,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i24.Future<List<_i15.Post>>.value(<_i15.Post>[]),
      ) as _i24.Future<List<_i15.Post>>);

  @override
  _i24.Future<_i15.Post> createPost(
    String? content,
    List<String>? images,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [
            content,
            images,
          ],
        ),
        returnValue: _i24.Future<_i15.Post>.value(_FakePost_13(
          this,
          Invocation.method(
            #createPost,
            [
              content,
              images,
            ],
          ),
        )),
      ) as _i24.Future<_i15.Post>);

  @override
  _i24.Future<void> likePost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #likePost,
          [postId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> unlikePost(String? postId) => (super.noSuchMethod(
        Invocation.method(
          #unlikePost,
          [postId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> addComment(
    String? postId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addComment,
          [
            postId,
            content,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i25.Comment>> getComments(String? postId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComments,
          [postId],
        ),
        returnValue: _i24.Future<List<_i25.Comment>>.value(<_i25.Comment>[]),
      ) as _i24.Future<List<_i25.Comment>>);

  @override
  _i24.Future<void> createComment(
    String? postId,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComment,
          [
            postId,
            content,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteComment(
    String? postId,
    String? commentId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteComment,
          [
            postId,
            commentId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i17.Chat>> getChats() => (super.noSuchMethod(
        Invocation.method(
          #getChats,
          [],
        ),
        returnValue: _i24.Future<List<_i17.Chat>>.value(<_i17.Chat>[]),
      ) as _i24.Future<List<_i17.Chat>>);

  @override
  _i24.Future<List<_i16.Message>> getChatMessages(String? chatId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatMessages,
          [chatId],
        ),
        returnValue: _i24.Future<List<_i16.Message>>.value(<_i16.Message>[]),
      ) as _i24.Future<List<_i16.Message>>);

  @override
  _i24.Future<_i16.Message> sendMessage(
    String? chatId,
    String? content,
    _i16.MessageType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [
            chatId,
            content,
            type,
          ],
        ),
        returnValue: _i24.Future<_i16.Message>.value(_FakeMessage_14(
          this,
          Invocation.method(
            #sendMessage,
            [
              chatId,
              content,
              type,
            ],
          ),
        )),
      ) as _i24.Future<_i16.Message>);

  @override
  _i24.Future<void> markChatAsRead(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #markChatAsRead,
          [chatId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteMessage(
    String? chatId,
    String? messageId,
    bool? deleteForEveryone,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMessage,
          [
            chatId,
            messageId,
            deleteForEveryone,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> reactToMessage(
    String? chatId,
    String? messageId,
    String? reaction,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactToMessage,
          [
            chatId,
            messageId,
            reaction,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> muteChat(
    String? chatId,
    bool? mute,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #muteChat,
          [
            chatId,
            mute,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i17.Chat> getOrCreateChat(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateChat,
          [userId],
        ),
        returnValue: _i24.Future<_i17.Chat>.value(_FakeChat_15(
          this,
          Invocation.method(
            #getOrCreateChat,
            [userId],
          ),
        )),
      ) as _i24.Future<_i17.Chat>);

  @override
  _i24.Future<void> deleteChat(String? chatId) => (super.noSuchMethod(
        Invocation.method(
          #deleteChat,
          [chatId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i18.MapPin> createMapPin({
    required double? latitude,
    required double? longitude,
    required String? type,
    String? title,
    String? description,
    bool? isPublic = true,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMapPin,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #type: type,
            #title: title,
            #description: description,
            #isPublic: isPublic,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i24.Future<_i18.MapPin>.value(_FakeMapPin_16(
          this,
          Invocation.method(
            #createMapPin,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #type: type,
              #title: title,
              #description: description,
              #isPublic: isPublic,
              #expiresAt: expiresAt,
            },
          ),
        )),
      ) as _i24.Future<_i18.MapPin>);

  @override
  _i24.Future<List<_i18.MapPin>> getNearbyMapPins({
    required double? latitude,
    required double? longitude,
    int? radius = 5000,
    String? type,
    List<String>? types,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyMapPins,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
            #type: type,
            #types: types,
          },
        ),
        returnValue: _i24.Future<List<_i18.MapPin>>.value(<_i18.MapPin>[]),
      ) as _i24.Future<List<_i18.MapPin>>);

  @override
  _i24.Future<List<_i18.MapPin>> getMyMapPins() => (super.noSuchMethod(
        Invocation.method(
          #getMyMapPins,
          [],
        ),
        returnValue: _i24.Future<List<_i18.MapPin>>.value(<_i18.MapPin>[]),
      ) as _i24.Future<List<_i18.MapPin>>);

  @override
  _i24.Future<void> deleteMapPin(String? pinId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMapPin,
          [pinId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> updateUserLocation({
    required double? latitude,
    required double? longitude,
    required bool? isVisible,
    String? status,
    String? statusMessage,
    double? speed,
    double? heading,
    double? altitude,
    double? accuracy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserLocation,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #isVisible: isVisible,
            #status: status,
            #statusMessage: statusMessage,
            #speed: speed,
            #heading: heading,
            #altitude: altitude,
            #accuracy: accuracy,
          },
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> toggleLocationVisibility(bool? isVisible) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLocationVisibility,
          [isVisible],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<dynamic> getNearbyLocations({
    required double? latitude,
    required double? longitude,
    int? radius = 10000,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyLocations,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
            #limit: limit,
          },
        ),
        returnValue: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<dynamic> getMyLocation() => (super.noSuchMethod(
        Invocation.method(
          #getMyLocation,
          [],
        ),
        returnValue: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<List<_i19.Story>> getStories({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStories,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i24.Future<List<_i19.Story>>.value(<_i19.Story>[]),
      ) as _i24.Future<List<_i19.Story>>);

  @override
  _i24.Future<_i19.Story> createStory({
    required String? mediaPath,
    required String? mediaType,
    int? duration = 24,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStory,
          [],
          {
            #mediaPath: mediaPath,
            #mediaType: mediaType,
            #duration: duration,
          },
        ),
        returnValue: _i24.Future<_i19.Story>.value(_FakeStory_17(
          this,
          Invocation.method(
            #createStory,
            [],
            {
              #mediaPath: mediaPath,
              #mediaType: mediaType,
              #duration: duration,
            },
          ),
        )),
      ) as _i24.Future<_i19.Story>);

  @override
  _i24.Future<void> viewStory(String? storyId) => (super.noSuchMethod(
        Invocation.method(
          #viewStory,
          [storyId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i14.User>> getStoryViews(
    String? storyId, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStoryViews,
          [storyId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i24.Future<List<_i14.User>>.value(<_i14.User>[]),
      ) as _i24.Future<List<_i14.User>>);

  @override
  _i24.Future<List<_i20.RidersRoute>> getPublicRoutes({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicRoutes,
          [],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i24.Future<List<_i20.RidersRoute>>.value(<_i20.RidersRoute>[]),
      ) as _i24.Future<List<_i20.RidersRoute>>);

  @override
  _i24.Future<List<_i20.RidersRoute>> getUserRoutes(
    String? userId, {
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserRoutes,
          [userId],
          {
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue:
            _i24.Future<List<_i20.RidersRoute>>.value(<_i20.RidersRoute>[]),
      ) as _i24.Future<List<_i20.RidersRoute>>);

  @override
  _i24.Future<_i20.RidersRoute> getRoute(String? routeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoute,
          [routeId],
        ),
        returnValue: _i24.Future<_i20.RidersRoute>.value(_FakeRidersRoute_18(
          this,
          Invocation.method(
            #getRoute,
            [routeId],
          ),
        )),
      ) as _i24.Future<_i20.RidersRoute>);

  @override
  _i24.Future<_i20.RidersRoute> createRoute({
    required String? name,
    String? description,
    required List<Map<String, dynamic>>? waypoints,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRoute,
          [],
          {
            #name: name,
            #description: description,
            #waypoints: waypoints,
            #isPublic: isPublic,
          },
        ),
        returnValue: _i24.Future<_i20.RidersRoute>.value(_FakeRidersRoute_18(
          this,
          Invocation.method(
            #createRoute,
            [],
            {
              #name: name,
              #description: description,
              #waypoints: waypoints,
              #isPublic: isPublic,
            },
          ),
        )),
      ) as _i24.Future<_i20.RidersRoute>);

  @override
  _i24.Future<void> shareRoute(
    String? routeId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #shareRoute,
          [
            routeId,
            userId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> deleteRoute(String? routeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoute,
          [routeId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<_i21.GroupChat>> getGroupChats() => (super.noSuchMethod(
        Invocation.method(
          #getGroupChats,
          [],
        ),
        returnValue:
            _i24.Future<List<_i21.GroupChat>>.value(<_i21.GroupChat>[]),
      ) as _i24.Future<List<_i21.GroupChat>>);

  @override
  _i24.Future<dynamic> createGroupChat({
    required String? name,
    String? description,
    bool? isPrivate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroupChat,
          [],
          {
            #name: name,
            #description: description,
            #isPrivate: isPrivate,
          },
        ),
        returnValue: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<_i21.GroupChat> getGroupChat(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getGroupChat,
          [id],
        ),
        returnValue: _i24.Future<_i21.GroupChat>.value(_FakeGroupChat_19(
          this,
          Invocation.method(
            #getGroupChat,
            [id],
          ),
        )),
      ) as _i24.Future<_i21.GroupChat>);

  @override
  _i24.Future<List<_i21.GroupMessage>> getGroupMessages(
    String? id, {
    int? limit = 50,
    DateTime? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMessages,
          [id],
          {
            #limit: limit,
            #before: before,
          },
        ),
        returnValue:
            _i24.Future<List<_i21.GroupMessage>>.value(<_i21.GroupMessage>[]),
      ) as _i24.Future<List<_i21.GroupMessage>>);

  @override
  _i24.Future<dynamic> sendGroupMessage({
    required String? groupId,
    required String? content,
    String? type = 'text',
    Map<String, double>? location,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendGroupMessage,
          [],
          {
            #groupId: groupId,
            #content: content,
            #type: type,
            #location: location,
          },
        ),
        returnValue: _i24.Future<dynamic>.value(),
      ) as _i24.Future<dynamic>);

  @override
  _i24.Future<void> attachRouteToGroup(
    String? groupId,
    String? routeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #attachRouteToGroup,
          [
            groupId,
            routeId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> updateGroupRideStatus(
    String? groupId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroupRideStatus,
          [
            groupId,
            status,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<Map<String, dynamic>>> getUserPosts(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPosts,
          [userId],
        ),
        returnValue: _i24.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i24.Future<List<Map<String, dynamic>>>);

  @override
  _i24.Future<void> addGroupMember(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addGroupMember,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> removeGroupMember(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeGroupMember,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String staticBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #staticBaseUrl,
          [],
        ),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.method(
            #staticBaseUrl,
            [],
          ),
        ),
      ) as String);

  @override
  String buildStaticUrl(String? path) => (super.noSuchMethod(
        Invocation.method(
          #buildStaticUrl,
          [path],
        ),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.method(
            #buildStaticUrl,
            [path],
          ),
        ),
      ) as String);

  @override
  _i24.Future<String> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i24.Future<String>.value(_i23.dummyValue<String>(
          this,
          Invocation.method(
            #getToken,
            [],
          ),
        )),
      ) as _i24.Future<String>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i26.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<void> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> register(
    String? username,
    String? email,
    String? password,
    String? fullName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            username,
            email,
            password,
            fullName,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> updateProfile(
    String? fullName,
    String? bio, [
    Map<String, dynamic>? motorcycleInfo,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [
            fullName,
            bio,
            motorcycleInfo,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> updateProfilePicture(String? imagePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfilePicture,
          [imagePath],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> updateUserStatus({
    String? message,
    String? customText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserStatus,
          [],
          {
            #message: message,
            #customText: customText,
          },
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<bool> checkAuthStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkAuthStatus,
          [],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  void addListener(_i27.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i27.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketService extends _i1.Mock implements _i28.SocketService {
  MockSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Stream<Map<String, dynamic>> get mapPinCreatedStream =>
      (super.noSuchMethod(
        Invocation.getter(#mapPinCreatedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get mapPinDeletedStream =>
      (super.noSuchMethod(
        Invocation.getter(#mapPinDeletedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get locationSharedStream =>
      (super.noSuchMethod(
        Invocation.getter(#locationSharedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get voiceUserJoinedStream =>
      (super.noSuchMethod(
        Invocation.getter(#voiceUserJoinedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get voiceUserLeftStream =>
      (super.noSuchMethod(
        Invocation.getter(#voiceUserLeftStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get voiceOfferStream => (super.noSuchMethod(
        Invocation.getter(#voiceOfferStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get voiceAnswerStream =>
      (super.noSuchMethod(
        Invocation.getter(#voiceAnswerStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get voiceCandidateStream =>
      (super.noSuchMethod(
        Invocation.getter(#voiceCandidateStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<List<dynamic>> get voiceExistingUsersStream =>
      (super.noSuchMethod(
        Invocation.getter(#voiceExistingUsersStream),
        returnValue: _i24.Stream<List<dynamic>>.empty(),
      ) as _i24.Stream<List<dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get messageReceivedStream =>
      (super.noSuchMethod(
        Invocation.getter(#messageReceivedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get groupMessageReceivedStream =>
      (super.noSuchMethod(
        Invocation.getter(#groupMessageReceivedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get messageReadStream =>
      (super.noSuchMethod(
        Invocation.getter(#messageReadStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get notificationReceivedStream =>
      (super.noSuchMethod(
        Invocation.getter(#notificationReceivedStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  _i24.Stream<Map<String, dynamic>> get locationUpdateStream =>
      (super.noSuchMethod(
        Invocation.getter(#locationUpdateStream),
        returnValue: _i24.Stream<Map<String, dynamic>>.empty(),
      ) as _i24.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateAuth(_i26.AuthProvider? auth) => super.noSuchMethod(
        Invocation.method(
          #updateAuth,
          [auth],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void requestMapPinSubscription() => super.noSuchMethod(
        Invocation.method(
          #requestMapPinSubscription,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void ensureConnected() => super.noSuchMethod(
        Invocation.method(
          #ensureConnected,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void subscribeToLocation(String? userId) => super.noSuchMethod(
        Invocation.method(
          #subscribeToLocation,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribeFromLocation(String? userId) => super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromLocation,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void joinGroup(String? groupId) => super.noSuchMethod(
        Invocation.method(
          #joinGroup,
          [groupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void leaveGroup(String? groupId) => super.noSuchMethod(
        Invocation.method(
          #leaveGroup,
          [groupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shareLocationToGroup(
    String? groupId,
    Map<String, dynamic>? locationData,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #shareLocationToGroup,
          [
            groupId,
            locationData,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void joinVoice(String? groupId) => super.noSuchMethod(
        Invocation.method(
          #joinVoice,
          [groupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void leaveVoice(String? groupId) => super.noSuchMethod(
        Invocation.method(
          #leaveVoice,
          [groupId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendVoiceOffer(
    String? toSocketId,
    dynamic offer,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendVoiceOffer,
          [
            toSocketId,
            offer,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendVoiceAnswer(
    String? toSocketId,
    dynamic answer,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendVoiceAnswer,
          [
            toSocketId,
            answer,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void sendVoiceCandidate(
    String? toSocketId,
    dynamic candidate,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #sendVoiceCandidate,
          [
            toSocketId,
            candidate,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i27.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i27.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i29.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isTracking => (super.noSuchMethod(
        Invocation.getter(#isTracking),
        returnValue: false,
      ) as bool);

  @override
  _i24.Future<bool> isLocationServiceEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isLocationServiceEnabled,
          [],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  _i24.Future<_i30.LocationPermission> requestPermission() =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPermission,
          [],
        ),
        returnValue: _i24.Future<_i30.LocationPermission>.value(
            _i30.LocationPermission.denied),
      ) as _i24.Future<_i30.LocationPermission>);

  @override
  _i24.Future<bool> hasPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasPermission,
          [],
        ),
        returnValue: _i24.Future<bool>.value(false),
      ) as _i24.Future<bool>);

  @override
  _i24.Future<_i30.Position?> getCurrentLocation() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i24.Future<_i30.Position?>.value(),
      ) as _i24.Future<_i30.Position?>);

  @override
  _i24.Future<void> startTracking({
    Duration? interval = const Duration(seconds: 30),
    bool? isVisible = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startTracking,
          [],
          {
            #interval: interval,
            #isVisible: isVisible,
          },
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void stopTracking() => super.noSuchMethod(
        Invocation.method(
          #stopTracking,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<void> updateLocation({
    required double? latitude,
    required double? longitude,
    bool? isVisible = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLocation,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #isVisible: isVisible,
          },
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> toggleVisibility(bool? isVisible) => (super.noSuchMethod(
        Invocation.method(
          #toggleVisibility,
          [isVisible],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<List<dynamic>> getNearbyUsers({
    required double? latitude,
    required double? longitude,
    int? radius = 5000,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyUsers,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
            #limit: limit,
          },
        ),
        returnValue: _i24.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i24.Future<List<dynamic>>);

  @override
  _i24.Stream<_i30.Position> getPositionStream() => (super.noSuchMethod(
        Invocation.method(
          #getPositionStream,
          [],
        ),
        returnValue: _i24.Stream<_i30.Position>.empty(),
      ) as _i24.Stream<_i30.Position>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WebRTCService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebRTCService extends _i1.Mock implements _i31.WebRTCService {
  MockWebRTCService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i24.Stream<List<String>> get participantsStream => (super.noSuchMethod(
        Invocation.getter(#participantsStream),
        returnValue: _i24.Stream<List<String>>.empty(),
      ) as _i24.Stream<List<String>>);

  @override
  _i24.Future<void> joinChannel(String? groupId) => (super.noSuchMethod(
        Invocation.method(
          #joinChannel,
          [groupId],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> leaveChannel() => (super.noSuchMethod(
        Invocation.method(
          #leaveChannel,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void toggleMute() => super.noSuchMethod(
        Invocation.method(
          #toggleMute,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GroupChatApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGroupChatApiService extends _i1.Mock
    implements _i11.GroupChatApiService {
  MockGroupChatApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_10(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i12.Dio);

  @override
  _i13.FlutterSecureStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFlutterSecureStorage_11(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i13.FlutterSecureStorage);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  set dio(_i12.Dio? value) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<List<_i21.GroupChat>> getGroupChats() => (super.noSuchMethod(
        Invocation.method(
          #getGroupChats,
          [],
        ),
        returnValue:
            _i24.Future<List<_i21.GroupChat>>.value(<_i21.GroupChat>[]),
      ) as _i24.Future<List<_i21.GroupChat>>);

  @override
  _i24.Future<Map<String, dynamic>> createGroupChat({
    required String? name,
    String? description,
    bool? isPrivate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroupChat,
          [],
          {
            #name: name,
            #description: description,
            #isPrivate: isPrivate,
          },
        ),
        returnValue:
            _i24.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i24.Future<Map<String, dynamic>>);

  @override
  _i24.Future<_i21.GroupChat> getGroupChat(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getGroupChat,
          [id],
        ),
        returnValue: _i24.Future<_i21.GroupChat>.value(_FakeGroupChat_19(
          this,
          Invocation.method(
            #getGroupChat,
            [id],
          ),
        )),
      ) as _i24.Future<_i21.GroupChat>);

  @override
  _i24.Future<List<_i21.GroupMessage>> getGroupMessages(
    String? id, {
    int? limit = 50,
    DateTime? before,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupMessages,
          [id],
          {
            #limit: limit,
            #before: before,
          },
        ),
        returnValue:
            _i24.Future<List<_i21.GroupMessage>>.value(<_i21.GroupMessage>[]),
      ) as _i24.Future<List<_i21.GroupMessage>>);

  @override
  _i24.Future<Map<String, dynamic>> sendGroupMessage({
    required String? groupId,
    required String? content,
    String? type = 'text',
    Map<String, double>? location,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendGroupMessage,
          [],
          {
            #groupId: groupId,
            #content: content,
            #type: type,
            #location: location,
          },
        ),
        returnValue:
            _i24.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i24.Future<Map<String, dynamic>>);

  @override
  _i24.Future<void> attachRoute(
    String? groupId,
    String? routeId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #attachRoute,
          [
            groupId,
            routeId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> updateRideStatus(
    String? groupId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRideStatus,
          [
            groupId,
            status,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> addMember(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMember,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> removeMember(
    String? groupId,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMember,
          [
            groupId,
            userId,
          ],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void log(String? message) => super.noSuchMethod(
        Invocation.method(
          #log,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String staticBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #staticBaseUrl,
          [],
        ),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.method(
            #staticBaseUrl,
            [],
          ),
        ),
      ) as String);

  @override
  String buildStaticUrl(String? path) => (super.noSuchMethod(
        Invocation.method(
          #buildStaticUrl,
          [path],
        ),
        returnValue: _i23.dummyValue<String>(
          this,
          Invocation.method(
            #buildStaticUrl,
            [path],
          ),
        ),
      ) as String);

  @override
  _i24.Future<String> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i24.Future<String>.value(_i23.dummyValue<String>(
          this,
          Invocation.method(
            #getToken,
            [],
          ),
        )),
      ) as _i24.Future<String>);
}

/// A class which mocks [MapPinProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMapPinProvider extends _i1.Mock implements _i32.MapPinProvider {
  MockMapPinProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i18.MapPin> get nearbyPins => (super.noSuchMethod(
        Invocation.getter(#nearbyPins),
        returnValue: <_i18.MapPin>[],
      ) as List<_i18.MapPin>);

  @override
  List<_i18.MapPin> get myPins => (super.noSuchMethod(
        Invocation.getter(#myPins),
        returnValue: <_i18.MapPin>[],
      ) as List<_i18.MapPin>);

  @override
  bool get isLoadingNearby => (super.noSuchMethod(
        Invocation.getter(#isLoadingNearby),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingMine => (super.noSuchMethod(
        Invocation.getter(#isLoadingMine),
        returnValue: false,
      ) as bool);

  @override
  bool get isCreatingPin => (super.noSuchMethod(
        Invocation.getter(#isCreatingPin),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void updateDependencies({
    required _i28.SocketService? socketService,
    required String? currentUserId,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateDependencies,
          [],
          {
            #socketService: socketService,
            #currentUserId: currentUserId,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i24.Future<void> loadNearbyPins({
    required double? latitude,
    required double? longitude,
    int? radius = 5000,
    List<String>? types,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadNearbyPins,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radius: radius,
            #types: types,
          },
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> reloadNearby() => (super.noSuchMethod(
        Invocation.method(
          #reloadNearby,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<void> loadMyPins() => (super.noSuchMethod(
        Invocation.method(
          #loadMyPins,
          [],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  _i24.Future<_i18.MapPin?> createPin({
    required String? title,
    String? description,
    required String? type,
    required double? latitude,
    required double? longitude,
    bool? isPublic = true,
    DateTime? expiresAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPin,
          [],
          {
            #title: title,
            #description: description,
            #type: type,
            #latitude: latitude,
            #longitude: longitude,
            #isPublic: isPublic,
            #expiresAt: expiresAt,
          },
        ),
        returnValue: _i24.Future<_i18.MapPin?>.value(),
      ) as _i24.Future<_i18.MapPin?>);

  @override
  _i24.Future<void> deletePin(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePin,
          [id],
        ),
        returnValue: _i24.Future<void>.value(),
        returnValueForMissingStub: _i24.Future<void>.value(),
      ) as _i24.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i27.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i27.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
